fix for camera
jabesq/netatmo-api-python pull request #13
Opened 2018-07-12 07:12 UTC by gieljnssns

fix for https://github.com/home-assistant/home-assistant/issues/15047#issuecomment-404087158
fix for:
```
2018-07-10 16:10:02 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up platform netatmo
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/binary_sensor/netatmo.py", line 74, in setup_platform
    if not data.get_camera_names():
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/netatmo.py", line 84, in get_camera_names
    self.update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/util/__init__.py", line 319, in wrapper
    result = method(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/netatmo.py", line 115, in update
    self.camera_data = lnetatmo.CameraData(self.auth, size=100)
  File "/srv/homeassistant/lib/python3.5/site-packages/smart_home/Camera.py", line 79, in __init__
    self.default_camera = list(self.cameras[self.default_home].values())[0]
IndexError: list index out of range
```

2018-07-12 12:06 UTC, jabesq requested changes
Small changes needed, but looks ok to me.
You will also need to rebase on top of tree

2018-07-12 12:06 UTC, jabesq commented on smart_home/Camera.py
> +                self.lastEvent[cam_id]['module_id'] == mod_id:
unneeded whitespace

2018-07-12 12:06 UTC, jabesq commented on smart_home/Camera.py
> +                        self.events[cam_id][time_ev]['module_id'] == mod_id:
unneeded whitespace

2018-07-12 12:06 UTC, jabesq commented on smart_home/Camera.py
> +                self.lastEvent[cam_id]['module_id'] == mod_id:
unneeded whitespace

2018-07-13 07:08 UTC, gieljnssns commented on smart_home/Camera.py
> +                self.lastEvent[cam_id]['module_id'] == mod_id:
When I do that, I get 
```
Error	Flake8	E127 — continuation line over-indented for visual indent	479:15
```

2018-07-13 07:08 UTC, gieljnssns commented on smart_home/Camera.py
> +                        self.events[cam_id][time_ev]['module_id'] == mod_id:
When I do that, I get 
```
Error	Flake8	E127 — continuation line over-indented for visual indent	503:22
```

2018-07-13 07:08 UTC, gieljnssns commented on smart_home/Camera.py
> +                self.lastEvent[cam_id]['module_id'] == mod_id:
When I do that, I get 
```
Error	Flake8	E127 — continuation line over-indented for visual indent	506:14
```

2018-07-13 07:19 UTC, gieljnssns commented
What will the new version number be?
So I can make a PR to HA...

2018-07-16 13:25 UTC, gieljnssns commented
> You will also need to rebase on top of tree

I hope I did it right

2018-07-17 08:01 UTC, jabesq approved these changes

2018-07-17 08:02 UTC, jabesq commented
There is still some conflict, I will do the rebase manually.
This will be release in version 1.1.1

2018-07-17 08:23 UTC, jabesq commented
Merge done manually

2018-07-17 08:23 UTC, closed without merging

2018-07-17 17:54 UTC, gieljnssns commented
> There is still some conflict, I will do the rebase manually.


Thanks

2018-07-23 15:00 UTC, Dennydd commented
Have new progress for this?i have Hassio whith Home Assistant 0.74.0 but the camera still does not work